### ISSUE TITLE
_.get is broken

### ISSUE THREAD

**Issue by odino** [Mohamed-amin/hand#3]
```
> _.get(null, 'a.b.c')
undefined
```

The whole point of `_.get` is to be able to safely evaluate expressions. For example, imagine you are calling an API and know that the only way to tell if the request was successful is by checking the body because it has a weird status code sent by the server:

``` js
makeApiCall(params, (err, res) => {
  if (_.get(res, 'body.result.code') === 'OPERATION_OK') {
     // ...
  }
})
```

Your current implementation will break this contract, as when there's a timeout on the server `res` is going to be undefined, thus throwing an exception on your side -- making `_.get` "unsafe".

**Comment by Mohamed-amin** [comment]
Thanks, 
Covered now with a test. https://github.com/Mohamed-amin/hand/pull/6
